language: generic
sudo: required
services:
  - docker

before-install:
  - docker build -t docker-frontend-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-frontend-react npm run test -- --coverge
